### ISSUE TITLE
Bios MD5

### ISSUE THREAD

**Issue by MikaXII** [recalbox/recalbox-manager#17]
Bios MD5 Hash
- If good bios -> text color green (only for hash column)
- If bad -> text color red

What do you think ?

**Comment by sveetch** [comment]
I prefer the way of blocking validation when the md5 hash is not the same than the one listed into the Manifest.

Changing behavior to accept any md5 and only mark valid/invalid bios file with color let the user doing "shit". Also there is a drawback to your behavior, this require to check md5 hash for every bios file when displaying the list, when there is many bios file on the disk, it can cause some performance issue.

Can you validate this new behavior and its drawback with recalbox community ?

**Comment by sveetch** [comment]
Ok so for now we stay on the current behavior.
