### ISSUE TITLE
Create a setup.py 

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-manager#22]
a setup.py script would be very usefull for recalbox buildroot https://docs.python.org/2/distutils/setupscript.html

**Comment by digitalLumberjack** [comment]
for info : 
configen setup.py (https://github.com/digitalLumberjack/recalbox-configgen/blob/master/setup.py)
 allows me to create a really simple buildroot mk file : https://github.com/digitalLumberjack/recalbox-buildroot/blob/unified/package/recalbox-configgen/recalbox-configgen.mk

**Comment by sveetch** [comment]
I know Python package you know :)

But fact is, a webapp is not a package, you can't really make it a package without encounter some troubles with static files, settings, uploaded medias, etc..

Commonly i release webapp with a Makefile and a clean "make install", but Makefile is not available on Recalbox. At least i can make you a shell script.

**Comment by digitalLumberjack** [comment]
make is more that available in recalbox, but not in the target system
We have to make a buildroot package, using make and make install

**Comment by sveetch** [comment]
I don't really know about your needs when you are within buildroot and all, let's talk about this on irc, maybe i can maintain some stuff to help you.
