### ISSUE TITLE
Add a link to the virtual gamepad application 

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-manager#24]
The virtual gamepad runs on port 8081

**Comment by sveetch** [comment]
Does the virtual gamepad app is running since system is fully started or is it something optionnal or the user need to enable in some sort of menu ?

If not automatically started, what can i use (a file to read ?) to know if it is running or not ?

**Comment by digitalLumberjack** [comment]
it's always running for now.

**Comment by rockaddicted** [comment]
The virtualgamepads default port is not 8081, but 8080 (8081 is the kodi's server port)
Can you correct it please?

**Comment by sveetch** [comment]
Shame on @digitalLumberjack !

Fixed with minor release 1.0.1
