### ISSUE TITLE
psutil + init.d script

### ISSUE THREAD

**Issue by MikaXII** [recalbox/recalbox-manager#29]
Je suis au taf je te la fais rapide il n'y a que comme ça que je peux communiquer.

1 - as tu des script init.d qui traîne ? Si oui ça m'aiderai beaucoup ^^.
2 - J'ai des problèmes avec psutil, doit t'il être obligatoirement installé via ton requirement.txt, ou je peux l'installer à part via package buildroot ?

**Comment by sveetch** [comment]
1) Je ne suis pas vraiment familier avec les script du genre "init.d", sachant aussi que tu ne risques pas d'en trouver sur le net qui nous conviennent à cause des limitations du raspberry, notre procédure d'utilisation se fait avec le serveur de développement livré dans Django (et pas un vrai serveur web en frontal de l'instance)., mais c'est totalement pas recommandé pour un usage en production. Il faudrait qu'on ait le temps de se parler sur IRC, au moins pour échanger nos emails pour en discuter (je serais pas très présent jusqu'à moitié de semaine prochaine mais trouverais le temps pour les mails);

2) J'avais vu avec @digitalLumberjack pour psutil et il avait justement intégré le package buildroot de psutil dans une bêta récente. Ma procédure est prévue pour l'utiliser https://github.com/sveetch/recalbox-manager#recalbox-system tu peux voir la ligne `virtualenv --system-site-packages .` qui fait en sorte de pas essayer de télécharger et compiler le package si il est déjà installé sur le système.

Donc si dans ton virtualenv, pip essaye de le retélécharger et le compiler (et du coup planter vu que y'a pas de compilateur sur Recalbox), c'est soit que tu bosses pas sur une version assez récente de Recalbox, soit tu utilises `make install` (qui sert que pour le dev) au lieu de la procédure dédié à Recalbox.

**Comment by sveetch** [comment]
Closing this, discussion continued in #36
