### ISSUE TITLE
CPU temperature in monitoring

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-manager#38]
Could be great !

@Sikahalv

**Comment by sveetch** [comment]
The psutil library we use to monitor system don't know anything about sensors, as it's probably not something consistent on every systems.

Seems there are some tricks, but again not consistent through every system, have to check http://stackoverflow.com/questions/2440511/getting-cpu-temperature-using-python

**Comment by substring** [comment]
found on the french wiki :
cat /sys/class/thermal/thermal_zone0/temp and divide by 1000
source : https://github.com/recalbox/recalbox-os/wiki/Commandes-linux-%28FR%29
