### ISSUE TITLE
Only show rom files and *.txt in rom directories

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-manager#40]
Bonjour 
les dossiers de roms contient des fichiers txt avec des informations à l'intérieur
ça serait bien de pouvoir les ouvrir pour les lire .

**Comment by sveetch** [comment]
Pour l'instant cela va au delà des fonctions de l'interface d'upload qui ne sert qu'à gérer les fichiers de rom/bios selon les règles apposées par le Manifest recalbox des systèmes d'émulations.

En soit ce n'est pas compliqué de lire des fichiers, mais il se pose alors le soucis de pouvoir distinguer les fichiers textes des fichiers binaires, ouvrir un fichier binaire pour lecture étant contre productif et inutile.

**Comment by Laddyacris** [comment]
Dans ce cas ça serait bien qu il n apparaissent pas personnellement je m attends soit à voir le contenu  de ce fichier affiché quelque part sur l interface soit les ouvrir pour obtenir des infos sur l upload

**Comment by sveetch** [comment]
Effectivement j'ai laissé la visualisation de tout les fichiers présents dans le dossier mais comme on n'a pas la capacité de différencier les fichiers textes lisibles des autres, il vaudrait mieux ne pas les afficher du tout. 

Avec cependant une petite possibilité pour lire des fichiers explicitement nommés avec une extension "*.txt".
