### ISSUE TITLE
[Cave Story]afficher les dossiers, créer un dossier 

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-manager#41]
Bonjour 
cave story , si on glisse dépose le dossier cave story , il uploade bien les fichiers mais ne conserve pas 
la même architecture de dossiers/fichiers.
ça serait bien qu'il conserve , ou qu'on est la possibilité de créer un dossier , l ouvrir et glisser les fichiers à l'interieur.
et que ceux ci soit visibles à l'affichage .

**Comment by sveetch** [comment]
Je ne connais rien à propos de ce "cave story", si c'est à considérer comme un nouveau système à part entière et non pas une rom, il faudra passer par des règles dans le Manifest recalbox.

Note aussi que l'interface d'upload est fait pour des fichiers, pas pour glisser des répertoires, donc le comportement est fort probablement pas ce que tu attendais. L'interface n'est pas un explorateur de fichiers.

**Comment by Laddyacris** [comment]
Ce n est pas une rom , il est constitué de dossiers et fichiers et si on upload le contenu de l archive ça ne fonctionne pas.
Je m attendais que pour chaque systeme affiché l upload fonctionne correctement.
Ce n est pas le cas puisse celui j ai pas comme les autres, et donc on est obligé de passer par winscp 
du coup pourquoi utilises le manager....

**Comment by sveetch** [comment]
Le but du manager est de faciliter l'usage aux novices, donc il suit des règles de filtrations depuis le Manifest Recalbox pour éviter les erreurs. Ce "cave story" n'est ni une rom, ni un système reconnu dans le manifest, donc forcément ça ne va pas fonctionner.

Par contre, si tu créé un dossier à la main dans le répertoire des systèmes, tu pourra uploader ce que tu veux, mais fichier par fichier. Le widget d'upload n'est pas fait pour recevoir des répertoires, seulement des fichiers.

L'interface ne permet pour l'instant que de créer des répertoires de systèmes d'émulation reconnus par le manifest, peut être un jour si j'ai le temps, je pourrais faire en sorte qu'on puisse créer librement des répertoires.
