### ISSUE TITLE
User friendly configuration editor

### ISSUE THREAD

**Issue by MaxCorpEnjoy** [recalbox/recalbox-manager#48]
Most users will not dig into the configuration file since it's not a gui.
Read the config file and displaying some kind of form could be a nicer way to display the configuration file.
It could be as simple as "$1=$2" => Label:$1, Value=$2.
Or even better, like checkboxes, for known variable $1, if we know there is a limited set of allower values $2.

Of course, having the choice to go bakc to the text view should be necessary (if we want to copy/paste or write some more complew stuff)

**Comment by sveetch** [comment]
It will need some work about standardization on these files before i can be able to parse it and use it concretly.

I'm not confident about managing this myself alone, because the config files and log seems to change often in various versions.

**Comment by sveetch** [comment]
Well it's a pleasant idea, but there is many config files and i dont have time for now to write a strong parser to be able to parse configs without any errors.

If someone can do a nice, working and strong parser, just as Python code (without to integrate it to the Django project), i would be able to start on something.

So for now, we will stay on "raw" editor.
