### ISSUE TITLE
[4.0.0] Some paths changed

### ISSUE THREAD

**Issue by substring** [recalbox/recalbox-manager#51]
root's home moved to /recalbox/share/system. Some files have moved too (logs, confs)
Some other paths must have changed, can't tell you all for now. Just ask if you need some more details

**Comment by sveetch** [comment]
I'm pinning this, we will move master and bump to a new major version for Recalbox 4.x and add a new branch for 3.3.x support

**Comment by sveetch** [comment]
Ok you can start editing these paths into branch https://github.com/recalbox/recalbox-manager/tree/recalbox_4-x until i'm able to work with Recalbox 4.0, then i would merge it in master definitively.

For now i will finish some things on https://github.com/recalbox/recalbox-manager/tree/recalbox_3-x

See file `project/settings.py` to add these paths changes.

**Comment by sveetch** [comment]
Oops, i should have not close the issue..

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-manager/pull/57

**Comment by sveetch** [comment]
This should be ok now
