### ISSUE TITLE
Virtual keyboard

### ISSUE THREAD

**Issue by daaa57150** [recalbox/recalbox-manager#64]
Hi,

The same way there is a virtual gamepad, it would be handy to have a virtual keyboard.

**Comment by sveetch** [comment]
Virtual gamepad is not part of recalbox-manager, i just linked to it on manager dashboard.

I'm sorry, this would be too much work for me since i don't ever have any time for now for manager features. I have to reject your issue, you should talk about your request on IRC channel.

**Comment by daaa57150** [comment]
Ok I didn't know that, I'm just discovering all that recalbox stuff

**Comment by sveetch** [comment]
no problemo

**Comment by robsdedude** [comment]
Please check out this forum post of mine:

https://forum.recalbox.com/topic/3482/virtual-keyboard

It might be of interest for you. I'm working on exactly what you asked for.
