### ISSUE TITLE
DMCA stuff in Manifest

### ISSUE THREAD

**Issue by ghost** [recalbox/recalbox-manager#69]
All download links to DMCA content needs to be removed from [MANIFEST.XML](https://github.com/recalbox/recalbox-manager/blob/master/project/MANIFEST.xml)

As they have been removed from the readme.txt files already. I would have done it myself, but I don't know the relations and dependencies of `MANIFEST.XML`

**Comment by sveetch** [comment]
Fixed since version 4.1 (currently in its own branch)
